// ── Read-aloud passage bank ("the lottery roll") ─────────────────────────────
// Section A of the San4 Score test used to be one fixed paragraph, so repeat
// takers memorised it and the pronunciation/pacing read stopped being honest.
// We now roll a random passage from 100+ each attempt. They're deliberately
// varied in topic and rhythm but held to a consistent difficulty and length
// (~40–65 words, ~25–35s aloud) so scores stay comparable across rolls.
//
// pickPassage() avoids the last few used (stored per device) so a user rarely
// gets the same one twice in a row.

export const PASSAGES = [
  // — Communication & speaking —
  'Good communication is not about using big words. It is about being understood. When you speak clearly and with confidence, people trust you more. They listen, they remember, and they act on what you say. The best speakers are not the loudest in the room. They are the ones who say the right thing, at the right time, in the simplest possible way.',
  'The most powerful word in any conversation is a pause. A short silence gives your listener time to absorb your point, and it gives you time to choose your next one. Speakers who rush fill the air with noise. Speakers who pause fill the room with meaning. Slow down, breathe, and let your words land.',
  'Confidence is not about having all the answers. It is about being comfortable when you do not. A confident speaker can say, "I am not sure, let me find out," without losing the room. People do not follow perfection. They follow calm, honest, steady voices that make them feel understood and respected.',
  'Every great conversation begins with listening. Before you try to be interesting, try to be interested. Ask a real question, then let the other person finish before you reply. When people feel heard, they open up, they trust you, and they remember how the conversation made them feel long after the words are gone.',
  'Clarity beats cleverness every single time. A message that is simple and clear will always travel further than one that is complex and impressive. If your listener has to work hard to understand you, you have not communicated, you have only performed. Say what you mean, mean what you say, and stop when you are done.',
  'Your voice carries more than words. It carries your mood, your energy, and your intent. A flat voice can make an exciting idea sound dull, while a warm voice can make a simple idea feel important. Practise varying your pace and your pitch, and your listeners will stay with you from the first word to the last.',
  'Nervousness and excitement feel almost the same in the body. Your heart races, your palms sweat, and your breath grows short. The difference is only in the story you tell yourself. Before you speak, try saying, "I am excited," instead of, "I am scared." That small shift can turn fear into fuel and doubt into energy.',
  'Feedback is a gift, even when it is hard to hear. The people who improve fastest are not the ones with the most talent. They are the ones who ask, "How can I do this better?" and then actually listen to the answer. Stay curious about your own weaknesses, and they will slowly turn into your strengths.',
  'A good story has a beginning, a middle, and a point. Too many people share every detail and forget the reason they started talking. Before you speak, ask yourself one question: what do I want the listener to feel or do at the end? Then cut everything that does not serve that single, simple goal.',
  'The words you choose shape the way people see you. Weak words like "maybe" and "I think" can make a strong idea sound uncertain. Firm, honest words make the same idea sound reliable. You do not need to be aggressive to sound sure. You only need to say what you believe, plainly and without apology.',

  // — Work & career —
  'The first few minutes of any meeting set the tone for everything that follows. Arrive prepared, greet people warmly, and know exactly what you want to achieve. A meeting without a goal is just an expensive conversation. When you lead with purpose, others follow, and the time you share becomes an investment rather than a cost.',
  'Great teams are not built on talent alone. They are built on trust. When people feel safe to share half-formed ideas, to disagree openly, and to admit mistakes, the whole team grows stronger. The best leaders spend less time giving orders and more time creating the conditions where good work can happen naturally.',
  'Deadlines are not the enemy of good work. They are its friend. A clear deadline forces you to decide what truly matters and to let go of what does not. Without one, projects drift and energy fades. Set honest timelines, protect them fiercely, and you will finish more and worry less along the way.',
  'The best way to solve a hard problem is to make it smaller. Break it into pieces you can actually hold, then tackle one piece at a time. A mountain looks impossible from the bottom, but every summit is reached one careful step after another. Progress, not perfection, is what carries you to the top.',
  'Your reputation is built in small moments, not big ones. It grows every time you answer an email on time, keep a quiet promise, or admit a mistake before anyone asks. People rarely remember the grand gestures. They remember whether they could count on you when it truly mattered, day after ordinary day.',
  'Networking is not about collecting business cards. It is about building real relationships, one honest conversation at a time. The goal is not to impress people with what you have done. It is to understand what they need and to see whether you can help. Give first, expect nothing, and the right doors will open on their own.',
  'A job interview is not an interrogation. It is a conversation between two people trying to find a good fit. Prepare your stories, but stay present enough to actually listen. The candidates who stand out are not the ones with perfect answers. They are the ones who are curious, honest, and genuinely easy to talk to.',
  'Saying no is one of the most important skills at work. Every yes you give to something unimportant is a no to something that matters. Protect your time the way you would protect money, because it is far more valuable and you can never earn it back. Focus is a form of respect for yourself.',
  'The strongest professionals are comfortable saying, "I do not know." Pretending to have every answer wastes time and erodes trust. Admitting a gap honestly, then promising to find out, shows both humility and reliability. People do not expect you to know everything. They expect you to be truthful about what you do not.',
  'Growth rarely feels comfortable. The tasks that stretch you are the ones that scare you a little, the ones just beyond your current skill. If your work always feels easy, you are coasting, not climbing. Seek out the challenges that make your heart beat faster, and you will look back amazed at how far you have come.',

  // — Learning & growth —
  'The fastest way to learn anything is to teach it to someone else. When you explain an idea out loud, you quickly discover the parts you only half understood. Teaching forces you to organise your thoughts, to fill the gaps, and to find simpler words. In helping others learn, you learn twice as much yourself.',
  'Mistakes are not the opposite of success. They are the path to it. Every expert you admire has failed more times than a beginner has even tried. The difference is that they treated each failure as a lesson rather than a verdict. Fall forward, take the lesson, and keep moving toward the thing you want.',
  'Habits are the invisible architecture of daily life. What you repeat, you become. A single good choice changes nothing, but a small choice repeated a thousand times can change everything. Do not wait for motivation to strike. Build a routine so simple that showing up is easy, and let consistency do the heavy lifting.',
  'Reading is a conversation with the smartest people who ever lived, across time and distance. In a few quiet hours you can absorb ideas that took someone a lifetime to discover. The habit costs almost nothing, yet it pays for the rest of your life. Read widely, think deeply, and your world will grow larger.',
  'Curiosity is the engine of a rich life. The people who stay interested in the world stay interesting to the world. They ask questions others are too proud to ask, and they wonder about things others take for granted. Never lose the childlike urge to understand how and why things really work.',
  'Discipline is choosing what you want most over what you want now. In the moment, comfort always looks more appealing than effort. But the life you dream of is built by the choices you make when no one is watching and nothing is forcing your hand. Small acts of discipline compound into something remarkable.',
  'The expert was once a beginner who refused to quit. Every skill that looks effortless was once clumsy and frustrating. When you feel like giving up, remember that the awkward stage is not a sign you are failing. It is proof that you are learning something genuinely new, and that is exactly where growth lives.',
  'Time is the one resource you cannot save, borrow, or buy back. You can only spend it, and you spend it whether you notice or not. The question is never whether you have enough time. The question is whether you are spending the time you have on the things that truly matter to you.',
  'Comparison is the thief of joy and the enemy of progress. There will always be someone ahead of you and someone behind. Measuring yourself against others tells you nothing useful about your own path. Compare yourself only to who you were yesterday, and let that quiet, honest measure be the one that guides you forward.',
  'A goal without a plan is only a wish. Dreaming is easy and costs nothing, but progress demands that you decide the very next step and then take it. Write down what you want, break it into actions, and begin today. The gap between where you are and where you want to be is simply action.',

  // — Nature & science —
  'The ocean covers most of our planet, yet we have explored only a small fraction of it. Its deepest trenches are darker and stranger than the surface of the moon. Down there, creatures glow with their own light and survive crushing pressure. The sea reminds us how much of our own world remains a mystery.',
  'Honeybees are among the most important workers on earth. As they gather nectar, they carry pollen from flower to flower, helping plants produce the fruits and seeds we depend on. A single hive can visit millions of flowers in a day. Without these tiny, tireless insects, much of our food would simply disappear.',
  'Light from distant stars takes years, sometimes millions of years, to reach our eyes. When you gaze up at the night sky, you are not seeing the stars as they are now. You are seeing them as they were long ago. In a very real sense, looking outward into space is also looking backward in time.',
  'Trees communicate with one another through a hidden network beneath the soil. Their roots connect through threads of fungus, sharing water, nutrients, and even warnings of danger. A forest is not a crowd of lonely individuals. It is a single, cooperating community, quietly supporting itself in ways we are only beginning to understand.',
  'The human brain uses about as much energy as a small light bulb, yet it is the most complex object we know of in the universe. It holds billions of cells, each connected to thousands of others. Every thought you have, every memory you keep, is a tiny storm of electricity crossing that vast, living network.',
  'Water is the quiet architect of our world. Over thousands of years it carves canyons through solid rock, shapes coastlines, and feeds every living thing. It is patient beyond imagining, wearing away mountains one drop at a time. Nothing on earth is softer than water, yet nothing is better at defeating what is hard.',
  'A single seed contains everything a plant needs to begin its life. Locked inside is a tiny map, waiting for warmth and water to wake it. From that quiet start can grow a tree that outlives the person who planted it. Great things often begin in forms so small we almost overlook them.',
  'The northern lights are one of nature’s most beautiful displays. They appear when tiny particles from the sun crash into gases high in our atmosphere, painting the night sky in ribbons of green and violet. For centuries, people told stories to explain them. Today we understand the science, yet the wonder has not faded at all.',
  'Every breath you take connects you to the plants around you. They release the oxygen you need, and they absorb the carbon dioxide you breathe out. It is a quiet exchange that has continued for millions of years. In a world that feels divided, the simple act of breathing ties all living things together.',
  'The pyramids of ancient times were built without modern machines, using only human effort, clever tools, and astonishing patience. Thousands of workers moved enormous stones across the desert and lifted them into place. That these structures still stand today, thousands of years later, is a testament to what determined people can achieve together.',

  // — History & ideas —
  'Every invention that changed the world began as a fragile idea that most people ignored. The printing press, the light bulb, the aeroplane, all were once dismissed as foolish or impossible. Progress depends on stubborn dreamers who keep working while others laugh. The future is built by those who refuse to accept that things cannot change.',
  'History is not a list of dates to memorise. It is a collection of human stories about courage, mistakes, and hard-won wisdom. When we study the past honestly, we see patterns that help us understand the present. Those who forget where they came from are far more likely to lose their way ahead.',
  'The wheel is one of the simplest and most important inventions in human history. Before it, everything had to be carried or dragged. After it, people could move goods, build machines, and travel further than ever before. It reminds us that the ideas which change everything are often surprisingly simple at their core.',
  'Language is perhaps humanity’s greatest invention. With nothing but sound, we can share ideas across cities, oceans, and centuries. A person who lived a thousand years ago can still speak to us through their written words. No other creature has found a way to pass its thoughts so freely from one mind to another.',
  'Money is a story we all agree to believe. A paper note has no value in itself, yet it can be exchanged for food, shelter, or almost anything else. It works only because we trust that others will accept it too. Much of civilisation rests on shared beliefs that we rarely stop to examine.',
  'The compass changed the course of human history. With a simple magnetic needle, sailors could find their way across open water, far from any coastline. Suddenly the world grew both larger and smaller, as distant lands became reachable. Sometimes the smallest tools open the widest doors to discovery and adventure.',
  'Democracy is a fragile and remarkable idea. It asks that ordinary people, with all their differences, share the power to shape their own future. It works only when citizens stay informed, speak honestly, and respect those who disagree. Like a garden, it must be tended constantly, or it slowly withers from neglect.',
  'The library of an ancient city was once the greatest store of knowledge in the world. Scholars travelled great distances to read its scrolls and share their ideas. Its loss reminds us how precious knowledge is, and how easily it can vanish. What one generation gathers, the next must protect and pass on.',
  'Maps have always been more than tools for finding the way. They reveal how people saw their world, including the places they feared and the ones they dreamed about. Old maps are full of mistakes and imagination, yet each one captures a moment when someone tried to make sense of a vast and puzzling planet.',
  'The idea of zero was a quiet revolution in mathematics. For a long time, people had no symbol for nothing, and calculation was clumsy and slow. Once zero was accepted, whole new fields of thought became possible. It is a beautiful reminder that even nothing, properly understood, can be worth a great deal.',

  // — Everyday life —
  'A cup of tea is a small ceremony repeated around the world. The warmth in your hands, the rising steam, the first quiet sip, these tiny rituals mark a pause in a busy day. Sometimes the most ordinary moments hold the most comfort, if only we slow down enough to truly notice them.',
  'Cooking a meal for someone is one of the oldest ways of showing care. It takes time, attention, and a little bit of yourself. The food may be simple, but the message behind it is powerful: I thought about you, and I wanted to give you something good. Kindness often travels best on a plate.',
  'A morning walk can change the shape of an entire day. The fresh air clears your head, the movement wakes your body, and the quiet gives your thoughts room to settle. You do not need special equipment or a distant destination. You only need to step outside and let your feet begin to move.',
  'Old friendships are like well-worn paths through a forest. You may not walk them every day, but they remain, ready whenever you return. Time and distance cannot erase the trust that was built through years of shared laughter and hardship. True friends pick up exactly where they left off, as if no time had passed.',
  'A garden teaches patience better than any book. You plant a seed, water it, and then you wait, day after day, with nothing to show. But quietly, beneath the soil, life is stirring. In time, green shoots appear, and you learn that some of the best things simply cannot be rushed into being.',
  'Rain has a way of slowing the whole world down. Streets grow quiet, people gather indoors, and the steady sound against the window invites us to rest. There is something honest about a rainy afternoon, a permission to pause. Not every day needs to be filled with doing. Some are meant simply for being.',
  'The smell of fresh bread can carry you straight back to childhood. Scent is tied more closely to memory than any of our other senses. A single familiar smell can unlock a whole scene, complete with faces, feelings, and the exact light of a long-ago afternoon. Our memories live not only in the mind, but in the body.',
  'A good night’s sleep is one of the simplest gifts you can give yourself. While you rest, your body repairs itself and your mind sorts through the day. Yet many of us treat sleep as something to sacrifice. In truth, almost every part of your waking life gets better when you finally learn to rest well.',
  'Small acts of kindness ripple further than we ever see. A warm word to a stranger, a door held open, a patient smile in a long queue, these cost nothing yet can change the course of someone’s day. You may never know the full reach of your kindness, but that is no reason to hold it back.',
  'There is a quiet joy in finishing a task you have been avoiding. The dread beforehand is almost always larger than the work itself. Once you begin, the weight lifts, the fog clears, and you wonder why you waited so long. Action, more than anything, is the cure for the anxiety of an unfinished job.',

  // — Motivation & mindset —
  'The only way to do great work is to care deeply about the work you do. Passion cannot be faked for long, and people can always tell the difference. When you love what you are building, the long hours feel lighter and the setbacks feel smaller. Find the work that lights you up, and pour yourself into it.',
  'Fear shrinks when you walk toward it and grows when you run away. The task you are avoiding is rarely as terrible as your imagination suggests. Take one small step in its direction, and the fear loosens its grip. Courage is not the absence of fear. It is the decision to act in spite of it.',
  'You do not have to be great to start, but you have to start to be great. Waiting for the perfect moment is just a comfortable way of never beginning. The perfect moment does not exist. There is only now, imperfect and available. Begin badly if you must, but begin, and improve as you go.',
  'Patience is not passive waiting. It is active trust that steady effort will pay off in time. In a world that promises instant results, patience feels almost old-fashioned. Yet almost everything worth having, from deep skill to strong relationships, is built slowly. Plant the seed, tend it faithfully, and let time do its quiet work.',
  'Your attitude is the one thing no circumstance can take from you. You cannot always choose what happens, but you can always choose how you respond. Two people can face the same hardship and walk away with completely different stories. The difference is not luck. It is the mindset each of them decides to carry.',
  'Success is rarely a straight line. It is a messy path full of wrong turns, dead ends, and unexpected detours. The people who reach the top are not the ones who never stumble. They are the ones who keep walking after they do. Progress is measured not by never falling, but by always rising again.',
  'Gratitude changes what you see. When you train yourself to notice what is good, your whole world seems to brighten, even when nothing outside has changed. The habit costs nothing and asks only a moment. Each night, name three things that went well, and slowly you will teach your mind to look for the light.',
  'The dream in your heart was placed there for a reason. It may feel too big, too distant, or too unlikely, but the size of a dream is not a reason to abandon it. It is a reason to begin. Take the first step, then the next, and trust that the path will reveal itself.',
  'Hard times do not last, but resilient people do. When life knocks you down, the goal is not to pretend it did not hurt. The goal is to feel it, learn from it, and slowly stand back up. Storms pass. What matters is who you choose to become while you are weathering them.',
  'Everyone you meet is fighting a battle you know nothing about. A little patience and a little kindness cost you almost nothing, yet they can mean everything to someone silently struggling. Choose to be gentle, especially when it is hard. In a world that can feel sharp and rushed, softness is a quiet kind of strength.',

  // — Technology & the modern world —
  'The internet has placed the knowledge of the world in your pocket. Never before has so much information been so easily reached by so many people. But information is not the same as wisdom. The real skill of our age is not finding answers. It is knowing which questions are worth asking in the first place.',
  'A smartphone is a remarkable tool and a demanding master. It can teach you almost anything, yet it can also steal hours you never meant to give. The device itself is neutral. What matters is whether you use it with intention, or whether you let it quietly use you, one notification at a time.',
  'Artificial intelligence is changing how we work, learn, and create. Like every powerful technology before it, it can be used to build or to harm. The tools do not decide our future. We do, through the choices we make about how to use them. The most important questions are not technical. They are human.',
  'Every message you send leaves a trace that can last far longer than you expect. The internet rarely forgets. Before you post in anger or share without thinking, pause and imagine those words read back to you years from now. A moment of care today can save you a great deal of regret tomorrow.',
  'Automation is taking over many routine tasks, and that frightens some people. But history suggests that when machines handle the repetitive work, humans are freed to do more creative and meaningful things. The challenge is not to fear the change. It is to prepare for it, and to keep learning the skills machines cannot easily copy.',
  'Behind every app on your phone are thousands of hours of careful, invisible work. Someone imagined it, someone designed it, and someone tested it again and again until it felt simple. True simplicity is not the absence of effort. It is the result of enormous effort, hidden so well that the user never has to see it.',
  'Data is often called the oil of the modern age, but it is far more personal than oil. It is made of your habits, your choices, and your private moments. Understanding how your information is collected and used is no longer optional. In a connected world, protecting your data is part of protecting yourself.',
  'Video calls have shrunk the distance between people in a way earlier generations could scarcely imagine. A face on a screen can bridge oceans in an instant. Yet nothing fully replaces sitting across a table from someone you love. Technology can connect us, but it is up to us to make those connections meaningful.',
  'The most useful websites and tools feel almost invisible. You forget you are using them, because they simply do what you need without getting in the way. Good design is quiet. It does not shout for your attention. It respects your time, anticipates your needs, and then gracefully steps aside.',
  'Online, it is easy to perform a life instead of living one. Carefully chosen photos rarely tell the whole story. Remember that you are comparing your ordinary, everyday reality to someone else’s highlight reel. Behind every perfect picture is a real person with the same doubts, struggles, and quiet hopes as you.',

  // — Health & the body —
  'Movement is medicine for both the body and the mind. You do not need a gym or an expensive plan. A brisk walk, a few stretches, a climb up the stairs, all of it counts. The best exercise is simply the one you will actually do, again and again, until it becomes a natural part of your life.',
  'What you eat becomes the fuel your body runs on and the material it rebuilds itself with. Small daily choices matter more than any dramatic diet. You do not need to be perfect. You only need to be a little more thoughtful, a little more often, and let those small choices add up over the years.',
  'Stress is not always the enemy. In small doses it sharpens your focus and pushes you to perform. The problem is stress that never switches off. Learning to rest, to breathe, and to step away is not laziness. It is maintenance, the same way a machine that never stops will eventually break down.',
  'Laughter really is a kind of medicine. It relaxes the body, lifts the mood, and reminds us not to take every difficulty so seriously. Even in hard times, a shared joke can ease the weight we carry. Never underestimate the healing power of a good laugh with people you trust.',
  'Drinking enough water is one of the simplest ways to feel better, yet it is easy to forget. Your body is mostly water, and even a small shortage can leave you tired and foggy. Keep a bottle nearby, sip often, and notice how something so ordinary can quietly improve almost every part of your day.',
  'The body keeps the score of everything we feel. Stress, worry, and grief do not stay only in the mind. They show up as tight shoulders, shallow breath, and restless sleep. Caring for your emotions is not separate from caring for your health. In truth, the two have never been apart at all.',
  'Rest is not a reward you earn after you are exhausted. It is a basic requirement for doing good work at all. A rested mind solves problems that a tired one cannot even see. Give yourself permission to stop before you are running on empty, and your effort will go much further.',
  'Deep breathing is a tool you carry with you everywhere, and it costs nothing. When you feel overwhelmed, a few slow breaths can calm your racing heart and clear your crowded mind. It is one of the oldest and simplest ways to steady yourself, always available, in any room, at any moment.',
  'Sunlight does more than brighten a room. It helps set the rhythm of your sleep, lifts your mood, and supports your health in quiet ways. A few minutes outdoors in the morning can reset your whole day. Sometimes the best remedy is the oldest one, simply stepping into the light.',
  'Taking care of your mind is just as important as taking care of your body. It is not weakness to ask for help when your thoughts feel heavy. It is wisdom. We would never tell someone with a broken leg to simply walk it off. Our minds deserve the same patience and care.',

  // — Travel & the wider world —
  'Travel teaches lessons no classroom can. When you step into an unfamiliar place, you see your own habits with fresh eyes. You learn that there are many good ways to live, to eat, and to greet a stranger. The world is far larger and far kinder than fear would have you believe.',
  'Every city has a rhythm of its own. Some move fast, restless and bright at every hour. Others move slowly, pausing for long meals and unhurried talk. Learning to feel a city’s rhythm, rather than fighting it, is the difference between a stressful visit and a journey you will remember for years.',
  'A shared meal is the fastest way to understand a new culture. Around a table, strangers become friends, language barriers soften, and stories flow more freely. The food may be unfamiliar, but the warmth of being welcomed is something every human heart recognises instantly. Hospitality is a language spoken everywhere.',
  'Mountains have a way of putting our worries into perspective. Standing before something so vast and so old, our daily troubles suddenly seem small. People have climbed toward high places for thousands of years, seeking not just the view, but the quiet clarity that comes from looking down on the world from above.',
  'Getting lost in an unfamiliar place is not always a problem to fix. Sometimes it is a chance to discover. Some of the best moments of any journey are the ones you never planned, the hidden street, the unexpected view, the conversation with a stranger. Leave a little room for the map to surprise you.',
  'Deserts seem empty at first glance, but they teem with quiet, hidden life. Plants store water through long droughts, and animals hunt only in the cool of night. There is a hard beauty in a place that asks so much of everything that lives there. The desert rewards patience and punishes the careless.',
  'Rivers have shaped human history more than almost any other feature of the land. People built their first cities along their banks, drawn by water, food, and easy travel. To follow a river from its source to the sea is to trace the very path along which civilisation itself once grew.',
  'A long train journey has a magic that faster travel cannot match. The world slides past the window, towns and fields and quiet stations, and time seems to soften. There is space to think, to read, to watch, and to simply be. Sometimes the journey itself is the most memorable part of the trip.',
  'Markets are the beating heart of many towns. Amid the colour, the noise, and the bargaining, you see a place at its most alive and honest. Vendors call out, neighbours gather, and the smell of fresh food fills the air. To wander a local market is to feel the true pulse of a community.',
  'The night sky looks completely different far from city lights. Away from the glow of streetlamps, thousands of stars appear, and the faint band of our galaxy stretches overhead. For most of history, every human being fell asleep beneath that view. It is worth travelling far, now and then, just to see it again.',

  // — Perseverance & character —
  'Character is what you do when no one is watching. It is easy to be honest and generous in public, where praise is on offer. The real test comes in private, in the small choices no one will ever see. Who you are in those quiet moments is who you truly are.',
  'Humility is not thinking less of yourself. It is thinking of yourself less. The most impressive people are often the ones who feel no need to impress. They listen more than they speak, they give credit freely, and they stay curious. Confidence and humility are not opposites. Together, they are quiet strength.',
  'The bamboo plant spends years growing roots underground before it shoots suddenly toward the sky. To an impatient observer, nothing seems to be happening. But beneath the surface, everything is being prepared. Your own growth may feel invisible for a long time, right up until the moment it becomes impossible to ignore.',
  'Forgiveness is not saying that what happened was acceptable. It is choosing to set down a weight that only you have been carrying. Holding onto anger harms you far more than the person who wronged you. To forgive is to free yourself, and to walk forward without the past clinging to your back.',
  'Integrity means your words and your actions tell the same story. When they match, people trust you without having to think about it. When they drift apart, that trust quietly erodes, no matter how impressive your words may sound. A promise kept is worth more than a hundred promises made.',
  'The strongest people are not those who never feel afraid. They are those who feel the fear fully and choose to act anyway. Courage is not a feeling. It is a decision, made again and again, often with a trembling voice and a pounding heart. Bravery and fear almost always travel side by side.',
  'Generosity is not about how much you have. It is about how open your hands are. Some of the most giving people have the least, and some of the wealthiest give nothing at all. What we share, more than what we keep, is the truest measure of the kind of person we have chosen to be.',
  'Consistency is quietly more powerful than intensity. A burst of effort followed by weeks of nothing rarely builds anything lasting. But a small, steady effort, repeated faithfully, can move mountains over time. Do not ask yourself how much you can do today. Ask what you can keep doing, day after day, for years.',
  'Real strength often looks like gentleness. It takes far more control to stay calm than to lash out, more courage to be kind than to be cruel. Anyone can be harsh in a moment of anger. It is the person who chooses patience and warmth, again and again, who is truly strong.',
  'The person you will become is being shaped right now, by ordinary choices you barely notice. Every book you read, every habit you keep, every word you speak is a small brick in the house of your future self. Build carefully. You are always, quietly, becoming someone. Make sure it is someone you respect.',
]

// How many of the most-recently-served passages to avoid repeating.
const RECENT_KEY = 'san4_passage_recent'
const AVOID = Math.min(8, Math.floor(PASSAGES.length / 3))

function readRecent() {
  try { return JSON.parse(localStorage.getItem(RECENT_KEY) || '[]') } catch { return [] }
}
function writeRecent(list) {
  try { localStorage.setItem(RECENT_KEY, JSON.stringify(list.slice(-AVOID))) } catch { /* ignore */ }
}

// Roll a random passage, skipping the last few this device has seen so repeat
// takers rarely get the same one twice. Records the pick before returning it.
export function pickPassage() {
  const recent = readRecent()
  const pool = PASSAGES.map((_, i) => i).filter(i => !recent.includes(i))
  const choices = pool.length ? pool : PASSAGES.map((_, i) => i)
  const idx = choices[Math.floor(Math.random() * choices.length)]
  writeRecent([...recent, idx])
  return PASSAGES[idx]
}
